version: '3'

services:
  app:
    # Configuração dos serviços da aplicação.
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql


  mysql:
    # Configuração do MySQL.
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: adoorei_checkout_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - desafio-backend-adoorei_mysql_data:/var/lib/mysql

volumes:
  desafio-backend-adoorei_mysql_data:
    # Boa prática: Usar volumes para armazenar dados persistentes e garantir a integridade dos dados em ambientes de produção.
